import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/Navbar';
import Footer from './components/Footer';
import { ReduxProvider } from './providers/ReduxProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Alternativa a Helvetica Narrow
const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto-condensed',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} font-sans min-h-screen flex flex-col antialiased`}
      >
        <div className="bg-[#1C1A1A]  ">
          <ReduxProvider>
            <Navbar />
            {children}
            <Footer />
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
